add solution for 05_lection3_03_calendar
js-tasks-ru/htmlcss-20210916_987456987p pull request #11
Opened 2021-10-01 19:27 UTC by Alex0889

2021-10-01 19:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-02 16:15 UTC, GSemikozov requested changes

2021-10-02 16:15 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item:nth-child(8) {
вместо такого варианта лучше проставить нужное количество пустых div-ов (разметка в действительности всегда будет генерироваться динамически, для каждого месяца отсчет дней будет не всегда с этой позиции)

2021-10-02 16:28 UTC, Alex0889 commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item:nth-child(8) {
fixed remark

2021-10-02 16:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-10-02 16:58 UTC, GSemikozov approved these changes

2021-10-02 16:59 UTC, merged