add solution for 03_lection1_02_accordion
js-tasks-ru/htmlcss-20210916_987456987p pull request #4
Opened 2021-09-22 05:28 UTC by Alex0889

2021-09-22 05:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-22 18:11 UTC, GSemikozov requested changes

2021-09-22 18:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin: 0 auto;
на уровне блока никаких внешних позиционирований согласно БЭМ :)

2021-09-22 18:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  border-radius: 10px;
8px по дизайну

2021-09-22 18:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 10px;
8px

2021-09-22 18:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  float: right;
про флоаты лучше забыть навеки и больше никогда их не применять)) как лучше сделать - расскажу скоро, а пока - можно обойтись без иконок.

2021-09-23 17:59 UTC, Alex0889 commented on 03-lection1/02-accordion/accordion.css
> +  margin: 0 auto;
fixed

2021-09-23 18:00 UTC, Alex0889 commented on 03-lection1/02-accordion/accordion.css
> +  border-radius: 10px;
fixed

2021-09-23 18:02 UTC, Alex0889 commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 10px;
fixed

2021-09-23 18:03 UTC, Alex0889 commented on 03-lection1/02-accordion/accordion.css
> +  float: right;
fixed))

2021-09-24 12:45 UTC, GSemikozov submitted a review, later dismissed

2021-09-24 12:45 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2021-09-24 14:19 UTC, GSemikozov approved these changes

2021-09-24 14:19 UTC, merged