add solution for 03_lection1_layout
js-tasks-ru/htmlcss-20210916_987456987p pull request #5
Opened 2021-09-22 15:29 UTC by Alex0889

2021-09-22 15:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-22 18:13 UTC, GSemikozov requested changes

2021-09-22 18:13 UTC, GSemikozov commented on assets/css/main.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap');
можно перенести определение в fonts.css

2021-09-22 18:13 UTC, GSemikozov commented on components/mainSection/mainSection.css
> +  height: 80vh;
это можно убрать - я скоро покажу несколько паттернов как прижать футер к низу экрана и растянуть центральную секцию на все доступное пространство

2021-09-23 17:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-23 18:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-23 18:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-23 20:42 UTC, Alex0889 commented on assets/css/main.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap');
fixed

2021-09-23 20:48 UTC, Alex0889 commented on components/mainSection/mainSection.css
> +  height: 80vh;
Solved using flexbox

2021-09-23 20:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-23 20:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-24 13:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-24 13:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-24 15:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-26 11:37 UTC, GSemikozov approved these changes

2021-09-26 11:37 UTC, merged